full_name=input("enter your name =")
age=int(input("enter your age ="))
city=input("enter your city = ")
hobby=input("enter your hobby = ")
print(f" meet {full_name} a 25 year old enthausist from {city} when not busy with daily task ,dev loves spending time {hobby} \nlife in {city} keeps {full_name} energetic and curious every single day \n with coding as a passon ,the future looks creative and inspiring for {full_name}in the {city} city ")