print("Enter the name of player 1=")
player_1=input("Name=")
print("NOW ENTER YOUR RUN")
run_1=int(input("Run="))
print("Enter the name of player 2=")
player_2=input("Name=")
print("NOW ENTER YOUR RUN")
run_2=int(input("Run="))
print("Enter the name of player 3=")
player_3=input("Name=")
print("NOW ENTER YOUR RUN")
run_3=int(input("Run="))
print("Enter the name of player 4=")
player_4=input("Name=")
print("NOW ENTER YOUR RUN")
run_4=int(input("Run="))
print("Enter the name of player 5=")
player_5=input("Name=")
print("NOW ENTER YOUR RUN")
run_5=int(input("Run="))
total_run=run_1+run_2+run_3+run_4+run_5
total_average=total_run//5
print("Toatal run score by all the 5 players are =",total_run)
print("Total average of all 5 players are =",total_average)